app:
  port: 8081
  secret_api_key: secret-admin-key
  secret_jwt_key: secret-note-diary

mail:
  host: smtp.gmail.com
  port: 587
  username: patiwatkongram@gmail.com
  password: sltsbqgpcblrqixd

db:
  driver: postgres
  username: postgres
  password: p@ssword@pgsql
  host: localhost
  port: 5432
  database: notediary